"""Map the upstream TH06 patch recipes to the installed NC scripts.

Inputs are local analysis files, never distributed game assets. Every translated
write is checked against an instruction boundary; missing entries fail closed.
"""
import argparse
import difflib
import json
import struct
from pathlib import Path

def align(a, b, key):
    matcher = difflib.SequenceMatcher(None, [key(x) for x in a], [key(x) for x in b], autojunk=False)
    for tag, x, end_x, y, end_y in matcher.get_opcodes():
        if tag == 'equal':
            yield from zip(range(x, end_x), range(y, end_y))
        elif tag == 'replace':
            # Match changed operands only when their opcode order agrees.
            sub = difflib.SequenceMatcher(None, [z['op'] for z in a[x:end_x]],
                                          [z['op'] for z in b[y:end_y]], autojunk=False)
            for i, j, n in sub.get_matching_blocks():
                yield from ((x+i+k, y+j+k) for k in range(n))

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('analysis', type=Path)
    parser.add_argument('output', type=Path)
    parser.add_argument('--scripts', type=Path, required=True, help='Extracted local NC ECL files (not distributed)')
    args = parser.parse_args()
    lines = ['// Generated by tools/generate_nc_ecl_map.py; no game script data.',
             'struct EclMap { int stage, oldOffset, oldSize, newOffset, newSize; bool timeline=false; };',
             'inline constexpr EclMap eclMap[] = {']
    sub_lines, frames, extra_times = [], [], []
    refs = {35,37,38,39,40,41,42,95,108,109,114,116}
    for stage in range(1,8):
        d = json.loads((args.analysis/f'stage{stage}_parsed.json').read_text())
        submap = {v:int(k) for k,v in d['new_to_old'].items()}
        # ST3's shared effect helper was shortened, but its callers and the
        # two sound instructions still identify sub 10 unambiguously.
        if stage == 3:
            submap[10] = 10
            submap[33] = 45  # Final Rainbow: original entry, now calls setup 46 and pattern 47.
        old, new = d['old'], d['new']
        def key(i):
            raw = bytes.fromhex(i['raw'])
            if i['op'] in refs or i['op'] in {2,3,29,30,31,32,33,34}:
                raw = raw[4:8] if i['op'] in refs else b''
            if i['op'] == 93: raw = b''
            return i['time'], i['op'], raw
        for old_sub, new_sub in sorted(submap.items()):
            sub_lines.append(f'{{{stage},{old_sub},{new_sub}}},')
            a, b = old['subs'][old_sub], new['subs'][new_sub]
            matches=list(align(a,b,key))
            matched={y:x for x,y in matches}
            for y,instruction in enumerate(b):
                if y in matched:continue
                following=next((z for z in range(y+1,len(b)) if z in matched),None)
                if following is not None and 0<=instruction['time']<=b[following]['time']:
                    extra_times.append(f'{{{stage},{a[matched[following]]["offset"]},{instruction["offset"]}}},')
            for x,y in matches:
                aa,bb=a[x],b[y]
                lines.append(f'{{{stage},{aa["offset"]},{12+len(bytes.fromhex(aa["raw"]))},{bb["offset"]},{12+len(bytes.fromhex(bb["raw"]))}}},')
        a,b=old['timelines'][0],new['timelines'][0]
        # Native timelines retain opcode order; spawn sub IDs are translated.
        def timeline_key(i):
            return i['op'], i['raw']
        time_map={}
        for x,y in align(a,b,timeline_key):
            aa,bb=a[x],b[y]
            lines.append(f'{{{stage},{aa["offset"]},{8+len(bytes.fromhex(aa["raw"]))},{bb["offset"]},{8+len(bytes.fromhex(bb["raw"]))},true}},')
            time_map[aa['time']]=bb['time']
        for old_time,new_time in sorted(time_map.items()): frames.append(f'{{{stage},{old_time},{new_time}}},')
    lines += ['};','struct SubMap { int stage, oldSub, newSub; };','inline constexpr SubMap subMap[] = {']+sub_lines+['};',
              'struct FrameMap { int stage, oldTime, newTime; };','inline constexpr FrameMap frameMap[] = {']+frames+['};',
              'struct ExtraTimeMap { int stage, oldFollowing, newOffset; };','inline constexpr ExtraTimeMap extraTimeMap[] = {']+extra_times+['};']
    lines += ['struct ScriptGuard { size_t size; uint64_t digest; };','inline constexpr ScriptGuard scriptGuards[] = {']
    for stage in range(1,8):
        data=(args.scripts/f'ecldata{stage}.ecl').read_bytes()
        digest=14695981039346656037
        for byte in data:digest=((digest^byte)*1099511628211)&0xffffffffffffffff
        lines.append(f'{{{len(data)},0x{digest:016x}ULL}},')
    lines.append('};')
    args.output.write_text('\n'.join(lines)+'\n',encoding='utf-8')

if __name__ == '__main__': main()
